# Generated by Django 3.0.1 on 2020-03-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='share_contact',
            field=models.BooleanField(default=False, help_text='Please indicate if you want to share contact information with visitors to the site.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(verbose_name='A brief description of the project'),
        ),
    ]
