# Generated by Django 3.0.1 on 2020-03-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200320_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content_type',
            field=models.CharField(blank=True, help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='share_contact',
            field=models.BooleanField(help_text='Please indicate if you want to share contact information with visitors to the site.', verbose_name='Show contact information on the web site'),
        ),
    ]
