# Generated by Django 3.0.1 on 2020-03-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200320_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='project',
            name='share_contact',
        ),
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='A private note to the site administrator (i.e. not the public)'),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.URLField(blank=True, help_text='Please provide the url to the source of the project (i.e on GitHub)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='http://xyz.com/', help_text='Please provide the url of the working project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='Screen shot of the application'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(verbose_name='A description of the project'),
        ),
    ]
